"""Added Memory Table

Revision ID: fd2457b430b0
Revises: 002
Create Date: 2026-06-25 15:54:25.718886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2457b430b0'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_content_tsv'), table_name='document_chunks', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_chunks_content_tsv'), 'document_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
